[package]
name = "snm-supernode"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
flate2 = "1"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snm-core = { workspace = true }
snm-transport = { workspace = true }
tar.workspace = true
thiserror.workspace = true
toml.workspace = true
