package com.doubleslash.client.ui

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color

/**
 * A peer's identicon, drawn from the SVG the shared core produced.
 *
 * The colour rules behind an avatar — islands, dual-hue modes, shade modes —
 * are intricate, and a second implementation of them here would drift from the
 * desktop's. So the core renders, and this parses what it rendered.
 *
 * That is only safe because the SVG is machine-generated by exactly one
 * function (`avatar_config::build_avatar_svg`) with a fixed shape: a square
 * viewBox of `grid` units, a background rect, then one rect per lit cell. The
 * parser is deliberately strict and falls back to a flat tint rather than
 * guessing, so a change to that function shows up as a plain square, not a
 * wrong picture.
 */
data class AvatarArt(val grid: Int, val background: Color, val cells: List<Cell>) {
    data class Cell(val x: Float, val y: Float, val size: Float, val color: Color)
}

/** Parse a core-rendered avatar SVG, or null if it is not the shape we expect. */
fun parseAvatarSvg(svg: String): AvatarArt? {
    val grid = RECT_ROOT.find(svg)?.groupValues?.get(1)?.toIntOrNull() ?: return null
    if (grid <= 0) return null

    val rects = RECT_CELL.findAll(svg).toList()
    if (rects.isEmpty()) return null

    // The first rect with a fill and no x/y is the background.
    var background = Color(0xFF2B2D31)
    val cells = mutableListOf<AvatarArt.Cell>()

    for (match in rects) {
        val attrs = match.value
        val fill = FILL.find(attrs)?.groupValues?.get(1)?.let(::parseHexColor) ?: continue
        val x = attrOf(attrs, "x")
        val y = attrOf(attrs, "y")
        if (x == null || y == null) {
            background = fill
            continue
        }
        val size = attrOf(attrs, "width") ?: 1f
        cells += AvatarArt.Cell(x, y, size, fill)
    }

    return if (cells.isEmpty()) null else AvatarArt(grid, background, cells)
}

/**
 * Draw a parsed avatar.
 *
 * The 18% corner radius matches the core's clip path, so a phone avatar has
 * the same silhouette as the same peer's on the desktop.
 */
@Composable
fun Avatar(art: AvatarArt, modifier: Modifier = Modifier) {
    Canvas(modifier.clip(RoundedCornerShape(percent = 18))) {
        val unit = size.minDimension / art.grid
        drawRect(color = art.background, size = size)
        art.cells.forEach { cell ->
            drawRect(
                color = cell.color,
                topLeft = Offset(cell.x * unit, cell.y * unit),
                // The core overshoots cells slightly to close sub-pixel seams;
                // scaling that overshoot keeps them closed at any size.
                size = Size(cell.size * unit, cell.size * unit),
            )
        }
    }
}

private val RECT_ROOT = Regex("""<svg[^>]*\swidth="(\d+)"""")
private val RECT_CELL = Regex("""<rect\b[^>]*/>""")
private val FILL = Regex("""fill="(#[0-9a-fA-F]{6})"""")

private fun attrOf(attrs: String, name: String): Float? =
    Regex("""\s$name="([0-9.]+)"""").find(attrs)?.groupValues?.get(1)?.toFloatOrNull()

private fun parseHexColor(hex: String): Color? =
    hex.removePrefix("#").toLongOrNull(16)?.let { Color(it or 0xFF000000L) }
