package com.doubleslash.client

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Optional "stay unlocked" storage for the identity file key.
 *
 * What is stored is the Argon2id-derived key that opens `identity.dat` — never
 * the passphrase. That key unlocks this one identity on this one device, so a
 * copy of it is worthless against any other file, and a passphrase the user
 * reused elsewhere never reaches disk.
 *
 * The key is sealed with an AES-256-GCM key held in the AndroidKeyStore, which
 * lives in hardware-backed storage on devices that have it and never leaves
 * the Keystore. That is a wrapping key rather than direct storage because the
 * Keystore deliberately will not hand a stored secret back out, and the core
 * needs the raw bytes. The sealed blob goes in app-private SharedPreferences:
 * useless without the Keystore key, which cannot be extracted from the device.
 *
 * The trade-off this exists to make, stated plainly: with it on, anything that
 * can run as this app on an unlocked phone can open the identity. With it off,
 * the identity file is inert without the passphrase. It is off until the user
 * turns it on.
 */
class IdentityVault(context: Context) {

    private val prefs =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    /** Whether a key is stored — i.e. whether the next launch skips the prompt. */
    fun hasKey(): Boolean = prefs.contains(PREF_SEALED)

    /**
     * Seal [fileKeyB64] — the core's `identity.export_key` reply — for reuse.
     *
     * Returns false if the Keystore refuses; the caller stays unlocked for
     * this run and prompts again next launch rather than reporting a success
     * that will not survive.
     */
    fun store(fileKeyB64: String): Boolean = runCatching {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())

        // GCM's IV is generated by the cipher (setRandomizedEncryptionRequired
        // is on by default) and is not secret, so it rides with the blob.
        val iv = cipher.iv
        val sealed = cipher.doFinal(fileKeyB64.toByteArray(Charsets.UTF_8))

        prefs.edit()
            .putString(PREF_SEALED, Base64.encodeToString(sealed, Base64.NO_WRAP))
            .putString(PREF_IV, Base64.encodeToString(iv, Base64.NO_WRAP))
            .commit()
    }.onFailure { Log.w(TAG, "could not seal the unlock key", it) }.isSuccess

    /**
     * Unseal the stored key, or null when there is none or it cannot be read.
     *
     * A key can stop opening: the Keystore entry is dropped when the user
     * removes their screen lock on some devices, and a restored backup carries
     * the prefs without the hardware key. Both are ordinary, not errors — the
     * stored blob is cleared and the caller falls back to the passphrase.
     */
    fun load(): String? {
        val sealed = prefs.getString(PREF_SEALED, null) ?: return null
        val iv = prefs.getString(PREF_IV, null) ?: return null

        return runCatching {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                wrappingKey(),
                GCMParameterSpec(GCM_TAG_BITS, Base64.decode(iv, Base64.NO_WRAP)),
            )
            String(
                cipher.doFinal(Base64.decode(sealed, Base64.NO_WRAP)),
                Charsets.UTF_8,
            )
        }.getOrElse { e ->
            Log.w(TAG, "stored unlock key could not be read — clearing it", e)
            clear()
            null
        }
    }

    /**
     * Forget the stored key and the Keystore key that sealed it.
     *
     * Deleting the wrapping key as well as the blob means "off" is off even if
     * a copy of the preferences file survives somewhere.
     */
    fun clear() {
        prefs.edit().remove(PREF_SEALED).remove(PREF_IV).commit()
        runCatching {
            KeyStore.getInstance(PROVIDER).apply { load(null) }.deleteEntry(KEY_ALIAS)
        }.onFailure { Log.w(TAG, "could not delete the Keystore entry", it) }
    }

    /** The Keystore key that seals the file key, created on first use. */
    private fun wrappingKey(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let {
            return it.secretKey
        }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // No user-authentication requirement: this feature exists to
                // remove a prompt, and gating it behind a second prompt would
                // defeat the point. The phone's own lock screen is the control
                // protecting it.
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val TAG = "IdentityVault"
        const val PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "conquerd.identity.kek"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
        const val PREFS_NAME = "identity_vault"
        const val PREF_SEALED = "sealed_key"
        const val PREF_IV = "sealed_iv"
    }
}
